# Generated by Django 4.2 on 2024-07-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_simplepost_simplecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplepost",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
